language: minimal
services:
- docker
deploy:
  provider: script
  script: ./push.sh
  on:
    tags: true
env:
  global:
  - secure: ALg19S0KHj8+89//R0G8Vpyr1UTrelb00mvDqX+SH0uIkF/w8ZHmcUApP08P33j0f+NbZZ91q3u4LLRlTVXaFxRsjHIQABfHpNAknEAwCYBM+tIb6ePtvYXLa+ppRNHWJ4i/fMBCvc2kQ95SWZUIDqlwfchUQSCUL0nFF3HuwTlseV8Um5APuuUmt9Gc9vPT6qj/LHtFwc/ZQfZE3oyezwU1WNn0io5WPV8qV1hip3R5JQRfE+dquMYgOTo8vRwEUFnCumN2Z/5523CMneR1pq5NG2jcmpDx4eP+XB/nodqb53aqBJnJtM1SETwf8zvAtxmc1mCbYD4vgatJyLSW41iYYcHZ4iLk6raNDQvvw5Vqq93RndOfd/IA059VmWLSakn6yJaOCyuh9EDoK+cL8vcmloWXSucxiv/z7ppNOg5iIpHspetyc7LINQkm2pt4lpBmyI4Ie3Fg1DOEWux6129nzhbuoDwv9RMUAwSUhRtsTbJDC0DRAtZ4AK2z7EAp0l+aY8Su57IcX4jhqIkZoqXjYaTToI11YQ3238Lk9nGZ0Op25rUfCXLSsbBjMdv4rdo6ZSbc+UwMRlHiBvqsrABODjStuurvgh6tmAmvq+kGsG4u4tsTK2gzZ1GHX/GP1WpdKRsN2rWTZAew+sIucNqQQ80cAjGOSVYQtbFSvoc=
  - secure: nP1BPtpTEDHcxr7LL5jlJRvjrs5I7p7Ilnfms/31Gjx+HjcPhY8mfvFfJ4g6JKhT7/rJujuOkRJOUSdKISeCY17u79CdFZ+1eV0fDz4FYDS/mB/1jI0jI0rK0Vj+ToVV46y5gqrM6RK63LSUgAcbcix4iK6Dg/xPBK2ANiASPd1BrjPJSBWe5i/bFi+tVo7X9aKXefdaevSXPYZB4Jy4sYNogXfTQi7clzfh2UhagMCn5zJ4Jrs6Hw6Kho2uX2a/pZRvSnQ0t3rpbvzxChAHs37C4PSDn4Y2pXywk7jVY+zneDZ/P9zOINFT+ZSzVHxauiqssJ8DQfYQl0zqEZ3PYqmW8irLmYMJxdKjBFsEJ7YcL2+C2XXPsWV5pibPfpXW5SSlWHw5nTPzWD1s0RVLQRqHz20HvCxB9rYhWOOhz9J0zsrLpJz67n2bJKdngieP3IPQHoFbLBORbvDqoLWJSYUPZphxkieT+RlIXvJ4TTo6EEQsHv0DeaHoAt1uwcn6fGAM8DRpyW6BAyjEa5j3SzYsWgvdUjhYzdOeUyaLF+qAhA617xEdBUTX46u3PfUfr8ifIW8/0nQHzHnWcdHSj8xRT6QUgiJQm4f8aF8BmdSUA8yCDICu2c3SnYkm7Yv8eTdP+nntCsvz2R7FSlgnxu1/PqsisJmoeXPVh2eS0ug=
